# Generated by Django 4.2.1 on 2023-07-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.IntegerField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sevicename', models.CharField(blank=True, max_length=50, null=True)),
                ('shortDecription', models.TextField(blank=True, max_length=250, null=True)),
                ('fullDecription', models.TextField(blank=True, max_length=1000, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile_image')),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolioImg')),
                ('shortDecription', models.TextField(blank=True, max_length=250, null=True)),
                ('fullDecription', models.TextField(blank=True, max_length=1000, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Expericence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('startyear', models.IntegerField()),
                ('passingyear', models.IntegerField()),
                ('Decription', models.TextField(blank=True, max_length=500, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('UniversityName', models.CharField(blank=True, max_length=250, null=True)),
                ('startyear', models.IntegerField()),
                ('passingyear', models.IntegerField()),
                ('gradepointsgained', models.DecimalField(decimal_places=2, max_digits=2)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('Decription', models.TextField(blank=True, max_length=500, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=70, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.TextField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolioImg')),
                ('shortDecription', models.TextField(blank=True, max_length=250, null=True)),
                ('fullDecription', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.yourdetails')),
            ],
        ),
    ]
