# Generated by Django 4.2.1 on 2023-07-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_alter_educations_gradepointsgained'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expericence',
            old_name='passingyear',
            new_name='Duration',
        ),
        migrations.RemoveField(
            model_name='expericence',
            name='startyear',
        ),
    ]
