# Generated by Django 4.2.1 on 2023-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_rename_passingyear_expericence_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourdetails',
            name='experienceYear',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
