# Generated by Django 4.2.1 on 2023-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_yourdetails_experienceyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_image'),
        ),
    ]
