# Generated by Django 4.2.1 on 2023-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_profileimage_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='clint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clintImg'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogImg'),
        ),
    ]
