# Generated by Django 4.2.1 on 2023-07-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_clint_image_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolioVideo'),
        ),
    ]
