# Generated by Django 4.2.1 on 2023-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0009_alter_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='fullDecription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
