# Generated by Django 4.2.1 on 2023-07-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0011_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
